### ISSUE TITLE
Modloader 0.8.6 dosen´t work issue

### ISSUE THREAD

**Issue by migomore** [xforce/anno1800-mod-loader#140]
Hi out there
The modloader files (python35.dll 1.749kb and python35_ubi.dll 4.323.kb) dosen´t work properly. First of all, they are exatly the same size as the latest I installed app 2 month ago, and when I wanted to start the game today, I saw that an update was being doenloaded on my ubisoft page (I was about to start the game after I opened ubisoft connect, and the download started automatically). So I went to download modloader 0.8.6, which I could see had been uploaded just 2 days ago. And I copy/pasted them into the bin directory. BUT when I start the game, all my lumberjack huts and charoral klins have dissapered, and the icon of those two is empty in the build menu at the bottom of the screen.
Is there a newer version of a different size than the ones I have mentioned above ???

**Comment by blastpv** [comment]
the files are ok. the problem in the old version of the mod is incompatible with these updates. please update your mods.

**Comment by Kevinatore** [comment]
Hey there, I just downloaded the latest Spice it Up Mod. And so far, the game is running again. However, all public moorings (Besucherhafen) are gone and they're also not available in the menu.

**Comment by blastpv** [comment]
> Hey there, I just downloaded the latest Spice it Up Mod. And so far, the game is running again. However, all public moorings (Besucherhafen) are gone and they're also not available in the menu.
> 
> Edit: I disabled all mods to see if the mods (like Habourlife) might cause the problem. And now, I get the error message again that the mod loader is not up to date :(

the verification steps are simple.

rename the mods folder to any other name to disable the loading of mods
We check the game files.
We start, if the problem does not start not in files and fashion, if it starts, point 4 is performed.
Download the 0.8.6 bootloader files and run it, if it doesn't start, the problem is in the bootloader. If point 5.
We return the mods folder and check the problem with the mod (probably uses the mod of more than one developer)
