### ISSUE TITLE
ANNO1800 dont Start with mod-loader v 0.8.6

### ISSUE THREAD

**Issue by ghostface36** [xforce/anno1800-mod-loader#141]
After Updating to Mode loader 0.8.6. Anno 1800 dont start more. 
I try with and withoud Mods. 
If i change to 0.8.5 and ignore update. Anno start. But without Mods.
Anno Version  GU14
What i make wrong?

**Comment by K2DO** [comment]
i posted this issue few days ago and it was removed im not sure why is that,
i have the same issue the game will not launch i get black screen and then it goes back to desktop ,
when i use the previous version it launches the game but when i load a save game it crashes because of the updates,
some people are saying to update spice it up may fix it, it didn't work for me,i guess the only option left is to get rid of this stupid mod and start over, i have tried almost everything no luck..

**Comment by blastpv** [comment]
the files are ok. the problem in the old version of the mod is incompatible with these updates. please update your mods.

**Comment by K2DO** [comment]
ok, this is what i just ended up doing, 
First, i disabled this mod  -[Gameplay]LoLItemsAddedToKetema
second, i installed the latest version of this mod all_slotables_unlocked_at_traders
this seems to fix my issue, hope this helps anyone .

Thanks.

**Comment by ghostface36** [comment]
> the files are ok. the problem in the old version of the mod is incompatible with these updates. please update your mods.

Spice it up is Up to date too. 
"After Updating to Mode loader 0.8.6. Anno 1800 dont start more.
I try with and withoud Mods." the MODS are not the problem ;)

**Comment by blastpv** [comment]
> > the files are ok. the problem in the old version of the mod is incompatible with these updates. please update your mods.
> 
> Spice it up is Up to date too. "After Updating to Mode loader 0.8.6. Anno 1800 dont start more. I try with and withoud Mods." the MODS are not the problem ;)

the verification steps are simple.
1. rename the mods folder to any other name to disable the loading of mods
2. We check the game files.
3. We start, if the problem does not start not in files and fashion, if it starts, point 4 is performed.
4. Download the 0.8.6 bootloader files and run it, if it doesn't start, the problem is in the bootloader. If point 5.
5. We return the mods folder and check the problem with the mod (probably uses the mod of more than one developer)

**Comment by ghostface36** [comment]
> 

I have try all this Yesterday 1000 times.... 
But today i make this like u wrote step by step. And it function. Anno run with Mods... thank u!

**Comment by blastpv** [comment]
> > 
> 
> I have try all this Yesterday 1000 times.... But today i make this like u wrote step by step. And it function. Anno run with Mods... thank u!

Happy to help
