### ISSUE TITLE
Mod Loader 8.6 (crash)

### ISSUE THREAD

**Issue by Dez2022** [xforce/anno1800-mod-loader#143]
I think everything looks okay, I press continue so that I can wait for the game to start however after several seconds during loading it got crash and returned to the desktop.

**Comment by blastpv** [comment]
the verification steps are simple.
1. rename the mods folder to any other name to disable the loading of mods
2. We check the game files.
3. We start, if the problem does not start not in files and fashion, if it starts, point 4 is performed.
4. Download the 0.8.6 bootloader files and run it, if it doesn't start, the problem is in the bootloader. If point 5.
5. We return the mods folder and check the problem with the mod (probably uses the mod of more than one developer)

**Comment by xforce** [comment]
Unable to reproduce
