### ISSUE TITLE
new version of mod loader

### ISSUE THREAD

**Issue by garignebean** [xforce/anno1800-mod-loader#146]
will there be a new version because of the update people started to have problems in-game . if there will be an update when will it be could you please enlighten us.

**Comment by blastpv** [comment]
the verification steps are simple.
1. rename the mods folder to any other name to disable the loading of mods
2. We check the game files.
3. We start, if the problem does not start not in files and fashion, if it starts, point 4 is performed.
4. Download the 0.8.6 bootloader files and run it, if it doesn't start, the problem is in the bootloader. If point 5.
5. We return the mods folder and check the problem with the mod (probably uses the mod of more than one developer)

**Comment by Verraco-de-hierro** [comment]
Dont't work sorry.

**Comment by blastpv** [comment]
> Dont't work. no way

it means you didn't do it right. this is a 100% working way.

**Comment by Kevinatore** [comment]
> Dont't work. no way. the error is given by the loader.

Hey, if you're using the Spice it Up mod:
They just released a new version today and now, everything's fine:
https://www.nexusmods.com/anno1800/mods/5?tab=files

In fact, the game launched properly again after renaming the mods folder. So the error was caused by the outdated mods themself.

**Comment by Verraco-de-hierro** [comment]
Okay. Thank you Kevinator. So that there are no errors in the charger, you have to follow the steps you say one after another.

Now some mods work and others don't but it's a problem with the mods and their updates.

Thanks for the solution.

greetings
