### ISSUE TITLE
comments inside of a operation node are not working

### ISSUE THREAD

**Issue by Miraak7000** [xforce/anno1800-mod-loader#15]
that's working:
```
<!--comment-->
<ModOp Type="add" Path="//Asset[Values/Standard/GUID=xxx]/some_path">
     <NodeToChange>xxx</NodeToChange>
</ModOp>
```

that's **not** working:
```
<ModOp Type="add" Path="//Asset[Values/Standard/GUID=xxx]/some_path">
     <!--comment-->
     <NodeToChange>xxx</NodeToChange>
     <!--comment-->
     <NodeToChange>xxx</NodeToChange>
     <!--comment-->
     <NodeToChange>xxx</NodeToChange>
</ModOp>
```

**Comment by kskudlik** [comment]
actually, I already mentioned it yesterday in #5 

@xforce answer was:
"About the comments, that should be handled by libxml2, it can parse the comments in recover mode, which is what I am using, but I could see there being a few issues, maybe it's a good idea to remove comments from the parse tree before doing any operations?! Not sure..."
https://github.com/GNOME/libxml2/ <- that lib is doing the xml-parsing and is a little bitchy about comments (and xml-errors too)

I´d recommend for the time being to just use a little script (or for example notepad++ replace) to remove those comments in the mod. You can still use them for a better overview in your "private version"

**Comment by Miraak7000** [comment]
Thanks for the hint. I haven't seen that.

**Comment by xforce** [comment]
I was taking a quick look earlier at the code, it could be that I am just handling the comment nodes incorrectly.
I will fix this soon, somehow.

**Comment by xforce** [comment]
Hmm, I didn't fix this specifically, but on my latest local copy this seems to produce the correct result

```
<ModOps>
     <ModOp Type="add" Path="//Asset[Values/Standard/GUID='101373']/Values">
        <!--comment-->
        <NodeToChange>xxx</NodeToChange>
        <!--comment-->
        <NodeToChange>xxx</NodeToChange>
        <!--comment-->
        <NodeToChange>xxx</NodeToChange>
    </ModOp>
</ModOps>
```

![b46180ac-fb21-44dc-a05d-5aeaa320b091](https://user-images.githubusercontent.com/1780766/58204691-b036e300-7c91-11e9-8fcb-116f7e2c83eb.png)

I did a small adjustment so that comments are now also in the output of the xml operations, before I was skipping everything from the beginning to the first actual node.

Let me know if there are still issues with comments after 0.3 is released.

**Comment by xforce** [comment]
This seems to be fixed.
