### ISSUE TITLE
New update 10.9.2019

### ISSUE THREAD

**Issue by Clamier** [xforce/anno1800-mod-loader#31]
HI first, I want to thank you for this amazing tool.
And can you please updated to new version which they released yesterday ?

**Comment by xforce** [comment]
As far as I am aware the modloader is working fine on the new update, I tested it myself with the Uplay version yesterday.  
Do not however that some mods may not work correctly anymore due to changes in some GUIDs which some mods reference, this was a change on BlueByte's part and there is not really anything I can do about it.  
The mod creators are already in the process of updating the mods to work with those changes.

If there are other issues please clarify, for mod specific issues you can always join this discord https://discord.gg/wnTEHbA where you can get in touch with quite a few of the actual mod creators.

**Comment by Clamier** [comment]
thanks ;)
