### ISSUE TITLE
Feature Request: validate/transpile an mod

### ISSUE THREAD

**Issue by desian78** [xforce/anno1800-mod-loader#34]
Hi,

 first up: great mod and tx for that.
This request is a little different from: issue https://github.com/xforce/anno1800-mod-loader/issues/5 what i see basicliy tests the functionality of mod-loader itself.

Idea is a tool for mod devs:
a command like:
`validate --mod-xml=/path/to/mod.xml --source=/path/to/asset.xml`
or/and  
`build --mod-xml=/path/to/mod.xml --source=/path/to/asset.xml --target/path/to/target.xml`

What should it do:
Gives hints like 
`path to '//Asset[Values/Standard/GUID='12345']/Values/foo/bar' not found. cannot merge. ignored.`
As a mod dev have a debug possibility.
or/and:
The xml is completly transpiled.
The mod dev can see the result without starting a new game every time a small change is made.

bg desian

**Comment by xforce** [comment]
While not having a really nice interface, the `xmltest` executable that is part of the mod loader released does quite a bit of this already.
If you run `xmltest mod.xml assets.xml` it will create a `patched.xml` in the current directory and will also print the usual warnings or errors as they are in the actual loader since `xmltest` uses the exact same code to parse and apply the `ModOps` 

Example:
![80752565-4567-4e18-9006-d74740b55266](https://user-images.githubusercontent.com/1780766/66248246-ae6a3b00-e6d9-11e9-9494-8a1caf881be6.png)

xmltest is also the tool I usually use when working on fixing bugs or adding new ways to handle xml patching.

**Comment by desian78** [comment]
nice...
So i change my feature request to:
Put this example in the documentation :-)
ty..

btw: a little syntax description with one or two examples (pe: how to use multible assets to change similar value(s)] would hep too
