### ISSUE TITLE
[Feature Request] merge_add Type

### ISSUE THREAD

**Issue by Serpens66** [xforce/anno1800-mod-loader#65]
I think a merge_add command, that is merging if there is already such an entry and otherwise is adding, is mandatory.

It would not only reduce the necessary modops needed, it would also make it more compatible to game updates and other mods.
Because when using "add", entries may be doubled (if other mod or game update also added them), while this problem does not happen with a merge_add command.

edit:
the more I create mods myself, the more I think this merge_add is needed. In fact with the current commands, you have to check every single bit your mod changes, if the devs made any change to it, and if so you might need to switch commands. This is really tedious work and unnecessarily can break mods.

**Comment by xforce** [comment]
I have my doubts, consider Mod A doing an add somewhere, and another using merge_add, expecting the thing to be added.
Which is a common thing currently being done with add, where you insert things into lists.
This will result in an impossible situation or broken behavior, because how _should_ I know that the previously with `add` added entry is not the entry you are looking for with `merge_add`.

Consider the following example:

```
<TestRoot>
<TestNode>
    <Text>Meow 1</Text>
</TestNode>
<TestNode>
    <Text>Meow 1</Text>
</TestNode>
</TestRoot>
```

```
// Mod A
<ModOp Type="add" Path="/TestRoot">
<TestNode>
    <Text>Meow 4</Text>
</TestNode>
</ModOp>
```

// Mod 3
```
<ModOp Type="merge_add" Path="/TestRoot">
<TestNode>
    <Text>Meow 1</Text>
</TestNode>
<TestNode>
    <Text>Meow 2</Text>
</TestNode>
<TestNode>
    <Text>Meow 3</Text>
</TestNode>
</ModOp>
```

Now how am I supposed to decide that in fact you didn't want to change the `TestNode` with `Meow 4` to `Meow 3`, but instead add a new `TestNode`?

I can understand how this might sound useful, but I think as proposed is way to fragile, where current merge already is too fragile in certain situations, but currently doesn't really interfere with any other operation provided.

Currently I do not see me implementing it. I will add a condition system however as per #28 

Maybe I am missing something here, or misunderstood, if so please let me know.
